---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-alloy:
    name: Lint Alloy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1
        with:
          repository: 'grafana/alloy'
          latest: true
          filename: 'alloy-linux-amd64.zip'
          extract: true
      - name: Move Alloy binary to path
        run: |
          mv alloy-linux-amd64 /usr/local/bin/alloy
          chmod +x /usr/local/bin/alloy
      - name: Run linting script
        run: './scripts/lint-alloy.sh'

  lint-editorconfig:
    name: Lint Editorconfig
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 'lts/krypton'
      - name: Install dependencies
        run: pnpm install
      - name: Run linting script
        run: './scripts/lint-editorconfig.sh'

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 'lts/krypton'
      - name: Install dependencies
        run: pnpm install
      - name: Run linting script
        run: './scripts/lint-markdown.sh'
