---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-alloy:
    name: Lint Alloy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1
        with:
          repository: 'grafana/alloy'
          latest: true
          filename: 'alloy-linux-amd64.zip'
          extract: true
      - name: Move Alloy binary to path
        run: |
          mv alloy-linux-amd64 /usr/local/bin/alloy
          chmod +x /usr/local/bin/alloy
      - name: Run linting script
        run: './scripts/lint-alloy.sh'

  lint-editorconfig:
    name: Lint Editorconfig
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 'lts/krypton'
      - name: Install dependencies
        run: pnpm install
      - name: Run linting script
        run: './scripts/lint-editorconfig.sh'

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 'lts/krypton'
      - name: Install dependencies
        run: pnpm install
      - name: Run linting script
        run: './scripts/lint-markdown.sh'
